apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eshoponweb-prod

resources:
  - ../../

nameSuffix: -prod

commonLabels:
  environment: production

replicas:
  - name: eshop-web
    count: 3
  - name: eshop-publicapi
    count: 3

configMapGenerator:
  - name: eshop-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Production

images:
  - name: eshopwebmvc
    newTag: stable
  - name: eshoppublicapi
    newTag: stable
